#############################################################################
# Makefile for building: diskdir.wcx
#############################################################################

all:
	lazbuild diskdir.lpi

clean:
	rm -f ../lib/*
	rm -f ../diskdir.wcx
