name: build-release

on:
  workflow_dispatch:
  release:
    types: [released]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-lin:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Lazarus
      run: sudo apt install lazarus

    - name: Install GTK library 
      run: sudo apt install libgtk2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
    
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Build packages
      run: ./build.sh

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: plugins-*.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
